#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Wed Dec 25 22:15:57 2013
#

import wx
import mp3play

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Frame(wx.Frame):
		def __init__(self, *args, **kwds):
				# begin wxGlade: Frame.__init__
				kwds["style"] = wx.DEFAULT_FRAME_STYLE
				wx.Frame.__init__(self, *args, **kwds)
				self.Play = wx.Button(self, wx.ID_ANY, _("Play"))
				self.Stop = wx.Button(self, wx.ID_ANY, _("Stop"))
				self.Previous = wx.Button(self, wx.ID_ANY, _("Previous"))
				self.Next = wx.Button(self, wx.ID_ANY, _("Next"))
				self.Playlist = wx.Button(self, wx.ID_ANY, _("Playlist"))
				self.slider_1 = wx.Slider(self, wx.ID_ANY, 0, 0, 10)
				self.__set_properties()
				self.__do_layout()
				# end wxGlade
				self.Bind(wx.EVT_BUTTON, self.OnPlay, self.Play)
				self.Bind(wx.EVT_BUTTON, self.OnStop, self.Stop)
				self.Bind(wx.EVT_BUTTON, self.OnPrevious, self.Previous)
				self.Bind(wx.EVT_BUTTON, self.OnNext, self.Next)
				self.Bind(wx.EVT_BUTTON, self.OnPlaylist, self.Playlist)
				self.playing = 0
		
		def __set_properties(self):
		    # begin wxGlade: Frame.__set_properties
		    self.SetTitle(_("PyMp3Player"))
		    self.SetSize((266, 140))
		    self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_3DLIGHT))
		    self.Play.SetMinSize((50, 50))
		    self.Stop.SetMinSize((50, 50))
		    self.Previous.SetMinSize((50, 50))
		    self.Next.SetMinSize((50, 50))
		    self.Playlist.SetMinSize((50, 50))
		    self.slider_1.SetMinSize((250, 30))
		    self.slider_1.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_3DLIGHT))
		    self.slider_1.SetForegroundColour(wx.Colour(0, 0, 255))
		    # end wxGlade
		
		def __do_layout(self):
		    # begin wxGlade: Frame.__do_layout
		    sizer_1 = wx.BoxSizer(wx.VERTICAL)
		    sizer_2 = wx.BoxSizer(wx.VERTICAL)
		    sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
		    sizer_3.Add(self.Play, 0, 0, 0)
		    sizer_3.Add(self.Stop, 0, 0, 0)
		    sizer_3.Add(self.Previous, 0, 0, 0)
		    sizer_3.Add(self.Next, 0, 0, 0)
		    sizer_3.Add(self.Playlist, 0, 0, 0)
		    sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)
		    sizer_2.Add(self.slider_1, 0, 0, 0)
		    sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
		    self.SetSizer(sizer_1)
		    self.Layout()
		    # end wxGlade
		
		def OnPlay(self, event):
				if self.mp3.isplaying():
						self.mp3.pause()
						self.Play.SetLabel("Play")
				elif self.mp3.ispaused():
						self.mp3.unpause()
						self.Play.SetLabel("Pause")
				else:		
						self.mp3.play()
						self.Play.SetLabel("Pause")

		def OnStop(self, event):
				self.mp3.stop()
				self.Play.SetLabel("Play")

		def OnPrevious(self, event):
				print "Not implemented\n"
				event.Skip()

		def OnNext(self, event):
				print "Not implemented\n"
				event.Skip()

		def OnPlaylist(self, event):
				print "Not implemented\n"
				event.Skip()

		def SetSong(self, mp3):
				self.mp3 = mp3

# end of class Frame
if __name__ == "__main__":
		gettext.install("app") # replace with the appropriate catalog name
		
		mp3 = mp3play.load("d:/temp.mp3")
		app = wx.PySimpleApp(0)
		wx.InitAllImageHandlers()
		frame_1 = Frame(None, wx.ID_ANY, "")
		app.SetTopWindow(frame_1)
		frame_1.SetSong(mp3)
		frame_1.Show()
		app.MainLoop()
